import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { GoogleGenerativeAI } from '@google/generative-ai';
import dotenv from 'dotenv';

dotenv.config();

const API_KEY = process.env.GOOGLE_API_KEY;
const MODEL_NAME = 'gemini-2.5-pro';
const DOC_PATH = path.resolve('docs', 'UPDATED_DOCUMENTATION.md');

if (!API_KEY) {
  console.error('❌ GOOGLE_API_KEY is missing in your .env file');
  process.exit(1);
}

const genAI = new GoogleGenerativeAI(API_KEY);

async function runDocumentationAgent() {
  try {
    console.log('🚀 Running AI doc generation agent...');

    const gitDiff = execSync('git diff HEAD~1 HEAD', { encoding: 'utf-8' }).trim();

    if (!gitDiff) {
      console.log('✅ No new changes detected. Skipping doc generation.');
      return;
    }

    console.log('🔍 Git diff found:\n', gitDiff);

    const existingDocs = fs.existsSync(DOC_PATH)? fs.readFileSync(DOC_PATH, 'utf-8'): '';
    const prompt = `
You are an AI documentation assistant.

The following is a git diff from a recent code update:
\`\`\`diff
${gitDiff}
\`\`\`

Here is the current technical documentation:
\`\`\`markdown
${existingDocs}
\`\`\`

Update the documentation **by modifying only the relevant sections**. If a new feature, route, or function is added, insert documentation for it in the appropriate section. Do NOT duplicate or re-write the entire doc. Maintain Markdown formatting.

Only return the updated, complete Markdown content.
`;

    console.log('🤖 Sending prompt to Gemini AI...');

    const model = genAI.getGenerativeModel({
      model: MODEL_NAME,
      apiVersion: 'v1beta',
    });

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const updatedMarkdown = response.text();

    fs.mkdirSync(path.dirname(DOC_PATH), { recursive: true });
    fs.writeFileSync(DOC_PATH, updatedMarkdown, 'utf-8');

    console.log(`✅ Documentation intelligently updated at: ${DOC_PATH}`);

    // === Git Commit and Push ===
    const commitMessage = 'docs: update autogenerated documentation';

    try {
      console.log('📦 Committing and pushing to GitHub...');
      execSync(`git add ${DOC_PATH}`, { stdio: 'inherit' });
      execSync(`git commit -m "${commitMessage}"`, { stdio: 'inherit' });
      execSync('git push', { stdio: 'inherit' });
      console.log('🚀 Changes pushed to GitHub.');
    } catch (gitError) {
      console.error('❌ Git commit/push failed:', gitError.message);
    }

  } catch (error) {
    console.error('❌ Error running documentation agent:', error);
  }
}

runDocumentationAgent();
